# Generated by Django 5.2.17 on 2026-10-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superMarket', '0002_alter_sold_product_t_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_product',
            name='ps_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
